data:
	@echo Generating 100 files
	@uv run python gendata.py

map:
	@echo Running map process


shuffle:
	@echo Running shuffle process

sort:
	@echo Sorting by keys
	sort -k1 -t, -o dfs/shuffle0/shuffle_0 dfs/shuffle0/shuffle_0
	sort -k1 -t, -o dfs/shuffle0/shuffle_1 dfs/shuffle0/shuffle_1
	sort -k1 -t, -o dfs/shuffle0/shuffle_2 dfs/shuffle0/shuffle_2
